### ISSUE TITLE
is there a possibility to include node_modules as part of the packaged zip

### ISSUE THREAD

**Issue by sragu** [threadheap/serverless-plugin-parcel#2]
We have issues with dynamic imports with lazy loading on one of our dependencies, parcel doesn't handle that package well. is it possible to include that as an external module in the zip?

In fact, I would prefer keeping all the node_modules as external, while there is an option to not build node_modules, I didn't find any way to add the non-dev node_modules in the generated zip file. 

Is there a way to achieve this?

**Comment by pavelvlasov** [comment]
@sragu I don't think it's possible in the current version of parcel (see [#44](https://github.com/parcel-bundler/parcel/issues/144)). We'll have to wait for parcel v2 for proper externals support.

**Comment by sragu** [comment]
Thanks for the response, will check back when Parcel 2 is out. For now, I have made a simple serverless plugin which does the same.
